const faqData = [ 
    {
        id : 1,
        question: "How do I create a Tap'Pay account?",
    answer: "Download the Tap’pay mobile app on app store or google play then proceed to create your e-wallet account."
   },
   {
    id : 2,
    question: "How do I become a Tap'Pay agent?",
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam venenatis, velit ac vehicula efficitur, enim lorem accumsan sapien, nec fringilla nibh risus nec velit. Etiam sodales augue in vehicula vehicula. Vivamus et pulvinar lectus. Maecenas nec tortor vitae nibh vestibulum mattis. Nulla euismod vitae turpis a consectetur. Donec laoreet sit amet neque id consequat. Pellentesque ultricies, augue sit amet commodo volutpat, ante sem vulputate libero, nec sollicitudin enim erat non elit. Curabitur pharetra, mi sit amet sagittis lobortis, metus sem placerat enim, non vulputate purus lectus quis erat. Nam facilisis tortor sed tincidunt iaculis.Nulla condimentum libero eget pharetra finibus. Sed laoreet accumsan arcu. Phasellus suscipit sollicitudin lorem, eget elementum urna tristique sed. In vulputate mattis enim, eget faucibus elit varius eleifend. Maecenas nibh nulla, venenatis id leo sed, pulvinar pharetra justo. Nam blandit id nisl vitae efficitur. Morbi efficitur a urna non efficitur. Etiam sed odio gravida, varius sem a, tincidunt lacus.Integer ultricies ultricies nisl eget eleifend. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam ultricies tempor nisi. Aenean id felis ut libero posuere vulputate quis quis ex. Pellentesque odio ligula, interdum non malesuada eu, ultricies id urna. Integer a mi tristique lorem ultrices volutpat. Nunc semper turpis in lacus eleifend ultrices. Nam neque quam, iaculis sed efficitur sed, auctor vitae neque. Proin et elementum ante. Maecenas tincidunt tristique mauris id porttitor. Vestibulum dui turpis, fringilla ac vehicula id, ultrices a leo."
   },
   {
    id : 3,
    question: "How can I get a Tap'Pay unit card?",
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam venenatis, velit ac vehicula efficitur, enim lorem accumsan sapien, nec fringilla nibh risus nec velit. Etiam sodales augue in vehicula vehicula. Vivamus et pulvinar lectus. Maecenas nec tortor vitae nibh vestibulum mattis. Nulla euismod vitae turpis a consectetur. Donec laoreet sit amet neque id consequat. Pellentesque ultricies, augue sit amet commodo volutpat, ante sem vulputate libero, nec sollicitudin enim erat non elit. Curabitur pharetra, mi sit amet sagittis lobortis, metus sem placerat enim, non vulputate purus lectus quis erat. Nam facilisis tortor sed tincidunt iaculis.Nulla condimentum libero eget pharetra finibus. Sed laoreet accumsan arcu. Phasellus suscipit sollicitudin lorem, eget elementum urna tristique sed. In vulputate mattis enim, eget faucibus elit varius eleifend. Maecenas nibh nulla, venenatis id leo sed, pulvinar pharetra justo. Nam blandit id nisl vitae efficitur. Morbi efficitur a urna non efficitur. Etiam sed odio gravida, varius sem a, tincidunt lacus.Integer ultricies ultricies nisl eget eleifend. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam ultricies tempor nisi. Aenean id felis ut libero posuere vulputate quis quis ex. Pellentesque odio ligula, interdum non malesuada eu, ultricies id urna. Integer a mi tristique lorem ultrices volutpat. Nunc semper turpis in lacus eleifend ultrices. Nam neque quam, iaculis sed efficitur sed, auctor vitae neque. Proin et elementum ante. Maecenas tincidunt tristique mauris id porttitor. Vestibulum dui turpis, fringilla ac vehicula id, ultrices a leo."
    }, 
    {
        id : 4,
        question: "What are the documents needed for registration?",
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam venenatis, velit ac vehicula efficitur, enim lorem accumsan sapien, nec fringilla nibh risus nec velit. Etiam sodales augue in vehicula vehicula. Vivamus et pulvinar lectus. Maecenas nec tortor vitae nibh vestibulum mattis. Nulla euismod vitae turpis a consectetur. Donec laoreet sit amet neque id consequat. Pellentesque ultricies, augue sit amet commodo volutpat, ante sem vulputate libero, nec sollicitudin enim erat non elit. Curabitur pharetra, mi sit amet sagittis lobortis, metus sem placerat enim, non vulputate purus lectus quis erat. Nam facilisis tortor sed tincidunt iaculis.Nulla condimentum libero eget pharetra finibus. Sed laoreet accumsan arcu. Phasellus suscipit sollicitudin lorem, eget elementum urna tristique sed. In vulputate mattis enim, eget faucibus elit varius eleifend. Maecenas nibh nulla, venenatis id leo sed, pulvinar pharetra justo. Nam blandit id nisl vitae efficitur. Morbi efficitur a urna non efficitur. Etiam sed odio gravida, varius sem a, tincidunt lacus.Integer ultricies ultricies nisl eget eleifend. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam ultricies tempor nisi. Aenean id felis ut libero posuere vulputate quis quis ex. Pellentesque odio ligula, interdum non malesuada eu, ultricies id urna. Integer a mi tristique lorem ultrices volutpat. Nunc semper turpis in lacus eleifend ultrices. Nam neque quam, iaculis sed efficitur sed, auctor vitae neque. Proin et elementum ante. Maecenas tincidunt tristique mauris id porttitor. Vestibulum dui turpis, fringilla ac vehicula id, ultrices a leo."
   },
   {
    id : 5,
    question: "How secure and safe is TaP'Pay?",
    answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam venenatis, velit ac vehicula efficitur, enim lorem accumsan sapien, nec fringilla nibh risus nec velit. Etiam sodales augue in vehicula vehicula. Vivamus et pulvinar lectus. Maecenas nec tortor vitae nibh vestibulum mattis. Nulla euismod vitae turpis a consectetur. Donec laoreet sit amet neque id consequat. Pellentesque ultricies, augue sit amet commodo volutpat, ante sem vulputate libero, nec sollicitudin enim erat non elit. Curabitur pharetra, mi sit amet sagittis lobortis, metus sem placerat enim, non vulputate purus lectus quis erat. Nam facilisis tortor sed tincidunt iaculis.Nulla condimentum libero eget pharetra finibus. Sed laoreet accumsan arcu. Phasellus suscipit sollicitudin lorem, eget elementum urna tristique sed. In vulputate mattis enim, eget faucibus elit varius eleifend. Maecenas nibh nulla, venenatis id leo sed, pulvinar pharetra justo. Nam blandit id nisl vitae efficitur. Morbi efficitur a urna non efficitur. Etiam sed odio gravida, varius sem a, tincidunt lacus.Integer ultricies ultricies nisl eget eleifend. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam ultricies tempor nisi. Aenean id felis ut libero posuere vulputate quis quis ex. Pellentesque odio ligula, interdum non malesuada eu, ultricies id urna. Integer a mi tristique lorem ultrices volutpat. Nunc semper turpis in lacus eleifend ultrices. Nam neque quam, iaculis sed efficitur sed, auctor vitae neque. Proin et elementum ante. Maecenas tincidunt tristique mauris id porttitor. Vestibulum dui turpis, fringilla ac vehicula id, ultrices a leo."
}, 
];

export default faqData;